services:
  backend:
    container_name: dev_nest_nuxt_sample_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: npm run start:dev
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: local
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD:
      DB_NAME: nest_nuxt_sample_development
    depends_on:
      - db
    volumes:
      - ./backend:/var/www
      # - /var/www/node_modules # コンテナ側の node_modules を優先
    ports:
      - "5002:5002"
    networks:
      - dev_nest_nuxt_sample_network
  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_nuxt_sample_development
    volumes:
      - dev_nest_nuxt_sample_postgres_data_volume:/var/lib/postgresql/data
    networks:
      - dev_nest_nuxt_sample_network

  frontend:
    container_name: dev_nest_nuxt_sample_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: development
    command: npm run dev -- -o
    volumes:
      - ./frontend:/var/www
      # - /var/www/node_modules # コンテナ側の node_modules を優先
    ports:
      - "9000:9000"
    stdin_open: true
    networks:
      - dev_nest_nuxt_sample_network

networks:
  dev_nest_nuxt_sample_network:

volumes:
  dev_nest_nuxt_sample_postgres_data_volume:
